### ISSUE TITLE
Make routing file path configurable

### ISSUE THREAD

**Issue by timbussmann** [ParticularLabs/NServiceBus.FileBasedRouting#11]
Currently the routing file name and path are configured by default and there is no way for users to configure them without messing around with the settings bag.

I think we could combine this with actually activating the feature. So instead of 

`configuration.EnableFeature<FileBasedRouting>();`

this should be either:

`configuration.EnableFileBasedRouting();`

or:

`configure.EnableFileBasedRouting(<pathToRoutingFile>);`

thoughts @SzymonPobiega @Scooletz @DavidBoike ?

**Comment by DavidBoike** [comment]
I like `configure.EnableFileBasedRouting(<pathToRoutingFile>);`

**Comment by DavidBoike** [comment]
And definitely dislike requiring the users to go anywhere near EnableFeature/DisableFeature.

**Comment by timbussmann** [comment]
> And definitely dislike requiring the users to go anywhere near EnableFeature/DisableFeature.

I was thinking the same. So we can actually consider making the feature private to enforce the usage of a more specialized API.

**Comment by timbussmann** [comment]
implemented by #13
