### ISSUE TITLE
Allow routing file to be loaded from a URI

### ISSUE THREAD

**Issue by timbussmann** [ParticularLabs/NServiceBus.FileBasedRouting#15]
If we enable the file to be loaded from an URI instead (or additionally) to a path, this would easily allow users to host their file on a simple server within their company for easier centralized routing management instead of having to create a shared folder or to redeploy the file.

Thoughts @DavidBoike @SzymonPobiega @Scooletz ?

**Comment by Scooletz** [comment]
👍 A simple server could be a `Consul cluster` with its KeyValue store, ensuring HA. There's web API for this https://www.consul.io/docs/agent/http/kv.html

**Comment by timbussmann** [comment]
Implemented with #19
