### ISSUE TITLE
Make refresh interval configurable

### ISSUE THREAD

**Issue by HEskandari** [ParticularLabs/NServiceBus.FileBasedRouting#22]
File-based routing is not always done so you can change the routes dynamically. It might be done as a way to centralize the route table but currently, the route is reloaded every few seconds.

Not thinking about the performance aspect of running the reflection code ever few seconds without caching in place, it might not even be desired.

**Comment by timbussmann** [comment]
> Not thinking about the performance aspect of running the reflection code ever few seconds without caching in place, it might not even be desired.

do you have a specific scenario where this can become an issue? When writing this code, the assumption was that parsing this file every few seconds is basically negligible.

**Comment by timbussmann** [comment]
additionally, taking your PR into account, I wonder whether a more appropriate API would allow you to change the interval instead of just setting a bool.

e.g. something like
`.UseFileBasedRouting(path, TimeSpan.FromMinutes(5))` 
or
`.UseFileBasedRouting(path, TimeSpan.Zero)` to never refresh

**Comment by SzymonPobiega** [comment]
👍 for Tim's interval proposal.

**Comment by HEskandari** [comment]
I'm :+1: for time-based interval as well. Mind you, parsing the file is okay, but there's no caching when discovering/loading types, etc. maybe if the 'Type.GetType' is cached it'd not be as major of an issue,

**Comment by timbussmann** [comment]
@HEskandari do you have performance measurements to share with us?

**Comment by HEskandari** [comment]
@timbussmann so just to be clear you're asking me to write the caching and compare it with simple Type.GetType and share the measurements? ;)

**Comment by timbussmann** [comment]
@HEskandari well, you're arguing that having no caching is a performance issue so I assumed you would have some kind of measurements (not necessarily data to compare to).

**Comment by HEskandari** [comment]
@timbussmann I was only suggesting that it _could potentially_ be an issue. I'm happy with the proposed resolution of time-based api to control the refresh.

**Comment by timbussmann** [comment]
@HEskandari cool, do you want to adjust your PR then?

**Comment by HEskandari** [comment]
@timbussmann sure, I'll do.

**Comment by HEskandari** [comment]
@timbussmann I had a look to update the PR, the current approach is to use 'RegisterStartupTask' which doesn't give me fine control on how often it should get called. 

Any pointers on how to execute that method every x seconds?

Another approach, since we're dealing with files, is to use a FileSystemWatcher and only update when the file is updated. 

There is yet another issue that seems to be missing that would potentially affect the design: Currently the removed entries from the routing file are not removed from the route table, as we only Add or Replace the entries read from the file, but won't remove the entries that existed in the old version that are not available in the current version.

Thoughts?

**Comment by SzymonPobiega** [comment]
@HEskandari the startup task uses a timer internally so you can pass the interval through the startup task to the timer. I think initially thought that the burden of using FileSystemWatcher is to high to be worth using it.

**Comment by timbussmann** [comment]
> I had a look to update the PR, the current approach is to use 'RegisterStartupTask' which doesn't give me fine control on how often it should get called.

not sure I understand. The startup task is only called once (at startup), you can pass the desired interval via parameter when registering the task, as proposed by @SzymonPobiega.

The FileSystemWatcher is an interesting idea, but would require additonal thoughts: e.g. .net core / standard compatbility. How well does it work with network folders and so on. Maybe raise a new issue as a feature request? For the issue addressed here, I think @SzymonPobiega is right.

**Comment by timbussmann** [comment]
> There is yet another issue that seems to be missing that would potentially affect the design: Currently the removed entries from the routing file are not removed from the route table, as we only Add or Replace the entries read from the file, but won't remove the entries that existed in the old version that are not available in the current version.

@HEskandari AddOrReplace replaces all routes registered with the given key with the new values provided. It doesn't use an "append" model. It's kinda like a Dictionary<Key, ReadOnlyCollection<Route>>, where you always have to include all previously existing routes when calling AddOrReplace with an already added key. Does that explanation make sense?

**Comment by HEskandari** [comment]
@timbussmann it does, thanks for the explanation
